<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="MutationRegister.aspx.cs" EnableEventValidation="false" Inherits="LandSurvey.Reports.MutationRegister" %>

<%@ Register Assembly="Syncfusion.EJ.Web, Version=17.1460.0.32, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89" Namespace="Syncfusion.JavaScript.Web" TagPrefix="ej" %>

<%@ Register TagPrefix="ej" Namespace="Syncfusion.JavaScript.Models" Assembly="Syncfusion.EJ" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <script src="../Scripts/jquery.validate.min.js"></script>
    <script src="../Scripts/ej.web.all.min.js"></script>
    <script src="../Scripts/ej.grid.min.js"></script>
    <script src="../Scripts/ej.unobtrusive.min.js"></script>
    <script src="../Scripts/jquery.validate.unobtrusive.min.js"></script>
    <link href="../Content/ej.widgets.core.min.css" rel="stylesheet" />
    <link href="../Content/ej.web.all.min.css" rel="stylesheet" />
    <style>
        .full-height {
            height: 100%;
        }

        .WordWrap {
            width: 100%;
            word-break: break-all;
        }
    </style>
    <script src="../Scripts/Validation.js" type="text/javascript"></script>
    <script type="text/javascript">  
        function Validation() {
            if (Required('<%=txtMutationSurveyNumber.ClientID%>', 'Mutation / Survey Number'))
                return true;
            return false;
        }

        function mergeHead(args) {
            args.headerCellMerge(2, 3, 4, 5, 6);
        }


    </script>
    <div>
        <div class="row" style="background-color: #f1c371; height: 35px; padding-top: 5px; border-radius: 5px 5px 5px 5px;">
            <div class="col-md-5">
                <label for="" style="color: saddlebrown; font-size: 18px;">Mutation Register</label>
                <label for="" style="color: white; font-size: 18px;" id="PopulationID"></label>
            </div>
            <%-- <div class="col-md-2">
                 <label for="" style="color:white;font-size: 18px;">बूथ संख्या :-</label>
                <label for="" style="color: white;font-size: 18px;" id="Booth_numberID"></label>
            </div>--%>
            <%--  <div class="col-md-2">
                 <label for="" style="color:white;font-size:18px;"> मतदारसंघ :</label>
                <label for="" style="color:white;font-size: 18px;" id="Vidhansabha_Id"></label>
            </div>--%>
        </div>
        <div>
            <h3></h3>
        </div>

        <%-- <asp:updatepanel id="UpdatePanel1" runat="server" xmlns:asp="#unknown">
         <Contenttemplate>--%>
        <div class="row">
            <div class="col-sm-2">
                Select Village :
            </div>
            <div class="col-sm-3">
                <asp:DropDownList ID="cmbVillage" runat="server" CssClass="form-control" Width="250px">
                </asp:DropDownList>
            </div>
            <div class="col-sm-2">
                <asp:RadioButtonList ID="rdbsearchtype" runat="server" RepeatDirection="Horizontal" Width="300px" Height="20px">
                    <asp:ListItem Value="Mutation" Selected="True">Mutation Number</asp:ListItem>
                    <asp:ListItem Value="Survey">Survey Number</asp:ListItem>
                </asp:RadioButtonList>
            </div>

        </div>
        <br />
        <div class="row">
            <div class="col-sm-2">
                Enter Mutation / Survey Number :
            </div>
            <div class="col-sm-3">

                <asp:TextBox ID="txtMutationSurveyNumber" runat="server" CssClass="form-control" Width="250px"></asp:TextBox>
            </div>
            <div class="col-sm-4">
                <asp:Button ID="btnShow" runat="server" Text="Show" Height="30px" Width="75px" OnClick="btnShow_Click" OnClientClick="javascript:return Validation();" />
                &nbsp;<asp:Button ID="btnExportToDoc" runat="server" Height="30px" Width="115px" Visible="false" OnClick="btnExportToDoc_Click" Text="Export to Word" />
                &nbsp;<asp:Button ID="btnExportToXls" runat="server" Height="30px" Width="115px" Visible="false" OnClick="btnExportToXls_Click" Text="Export to Excel" />
            </div>
        </div>



        <%-- </Contenttemplate>
        </asp:updatepanel>--%>
        <br />
        <%--        <asp:UpdatePanel ID="updatepn2" runat="server"> 
             <ContentTemplate> --%>



        <div id="divReport" runat="server">
            <font size="2" face="Arial Unicode MS">
                 
            <%--OnSelectedIndexChanged="grdMutationFinal_SelectedIndexChanged"  DataKeyNames="mutationid" CssClass="table table-striped table-bordered table-condensed"
                OnRowDataBound="grdMutationFinal_RowDataBound" OnRowDeleting="grdMutationFinal_RowDeleting" AutoGenerateDeleteButton="true"--%>

            <asp:GridView ID="grdMutationFinal" runat="server" AllowPaging="True" PageSize="5" OnPageIndexChanging="grdMutationFinal_PageIndexChanging" Width="988px" DataKeyNames="mutationno, villagecode"
                 AutoGenerateColumns="false" OnRowDataBound="grdMutationFinal_RowDataBound">
                <Columns>
                    <asp:BoundField DataField="mutationyear" HeaderText="सन" />
                    <asp:BoundField DataField="mutationno" HeaderText="फेरफार क्र." />
                    <asp:TemplateField HeaderText="विवरण">
                        <ItemTemplate>
                            <div style="width: 500px; height: 100px;">
                                <%#Eval("mutationdetail") %>
                            </div>
                            <br />
                            <asp:GridView ID="grdMutationChild" ShowHeader="false" Width="500px" runat="server" AllowPaging="false"
                                CssClass="table table-striped table-bordered table-condensed" AutoGenerateColumns="false">
                                <Columns>
                                    <asp:BoundField DataField="mutationdetail" HeaderText="mutationdetail" />
                                    <asp:BoundField DataField="field4" HeaderText="field4" />
                                    <asp:BoundField DataField="field5" HeaderText="field5" />
                                </Columns>
                            </asp:GridView>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <%-- <asp:BoundField DataField="csurveyno" ItemStyle-CssClass="word-break: break-all;" HeaderText="सर्व्हे क्र" />--%>
                    <asp:TemplateField HeaderText="सर्व्हे क्र">
                        <ItemTemplate>
                            <div class="WordWrap">
                                <%#Eval("csurveyno") %>
                            </div>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
         </font>
        </div>

        <ej:Grid ID="Grid1" runat="server" AllowPaging="True" Visible="false" IsResponsive="True" OnServerPdfExporting="Grid1_ServerPdfExporting" AllowTextWrap="true">
            <ToolbarSettings ShowToolbar="true" ToolbarItems="excelExport,wordExport,pdfExport"></ToolbarSettings>
            <PageSettings PageSize="5"></PageSettings>
            <ClientSideEvents MergeHeaderCellInfo="mergeHead" />
            <Columns>
                <ej:Column Field="mutationyear" HeaderText="सन" Width="50" />
                <ej:Column Field="mutationno" HeaderText="फेरफार क्र." Width="50" />
                <ej:Column Field="mutationdetail" HeaderText="विवरण" Width="400" AllowTextWrap="true" />
                <ej:Column Field="field4" HeaderText="" Width="10" />
                <ej:Column Field="field5" HeaderText="" Width="10" />
                <ej:Column Field="field6" HeaderText="" Width="10" />
                <ej:Column Field="surveynos" HeaderText="सर्व्हे क्र" Width="300" />
            </Columns>
        </ej:Grid>
        <%--</contenttemplate>
              <Triggers> 
              <asp:PostBackTrigger controlid="Grid1"/> 
             </Triggers> 
        </asp:updatepanel>--%>
        <br />
        <br />
        <br />
    </div>
</asp:Content>
