<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="SolicitorApproval.aspx.cs" Inherits="LandSurvey.Solicitor.SolicitorApproval" %>

<%@ Register Assembly="Syncfusion.EJ" Namespace="Syncfusion.JavaScript.Models" TagPrefix="ej" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <script src="../Scripts/jquery.validate.min.js"></script>
    <script src="../Scripts/ej.web.all.min.js"></script>
    <script src="../Scripts/ej.grid.min.js"></script>
    <script src="../Scripts/ej.unobtrusive.min.js"></script>
    <script src="../Scripts/jquery.validate.unobtrusive.min.js"></script>
    <link href="../Content/ej.widgets.core.min.css" rel="stylesheet" />
    <link href="../Content/ej.web.all.min.css" rel="stylesheet" />
    <style>
        .full-height {
            height: 100%;
        }
    </style>
    <script src="../Scripts/Validation.js" type="text/javascript"></script>
    <script type="text/javascript">  

</script>
    <div>
        <div class="row" style="background-color: #f1c371; height: 35px; padding-top: 5px; border-radius: 5px 5px 5px 5px;">
            <div class="col-md-5">
                <label for="" style="color: saddlebrown; font-size: 18px;">Document Scrutiny and Approval</label>
                <label for="" style="color: white; font-size: 18px;" id="PopulationID"></label>
            </div>
            <%-- <div class="col-md-2">
                 <label for="" style="color:white;font-size: 18px;">बूथ संख्या :-</label>
                <label for="" style="color: white;font-size: 18px;" id="Booth_numberID"></label>
            </div>--%>
            <%--  <div class="col-md-2">
                 <label for="" style="color:white;font-size:18px;"> मतदारसंघ :</label>
                <label for="" style="color:white;font-size: 18px;" id="Vidhansabha_Id"></label>
            </div>--%>
        </div>
        <div>
            <h3></h3>
        </div>
        <%-- <asp:updatepanel id="UpdatePanel1" runat="server" xmlns:asp="#unknown">
         <Contenttemplate> <br />--%>
        <div class="row">
            <div class="col-sm-2">
                Select Village :
            </div>
            <div class="col-sm-3">
                <asp:DropDownList ID="cmbVillage" runat="server" CssClass="form-control" Width="250px">
                </asp:DropDownList>
            </div>
            <div class="col-sm-2">
                Select Document Number :
            </div>
            <div class="col-sm-2">
                <asp:DropDownList ID="cmdDocumentNumber" runat="server" AutoPostBack="true" OnSelectedIndexChanged="cmdDocumentNumber_SelectedIndexChanged" CssClass="form-control" Width="250px">
                </asp:DropDownList>
                <asp:Label ID="lblIteration1" runat="server" Text="1" Visible="false"></asp:Label>
                <asp:Label ID="lblIteration2" runat="server" Text="" Visible="false"></asp:Label>
                <asp:Label ID="lblIteration3" runat="server" Text="" Visible="false"></asp:Label>
            </div>
        </div>


        <%-- </Contenttemplate>
        </asp:updatepanel>--%>
        <br />
        <%--        <asp:UpdatePanel ID="updatepn2" runat="server"> 
             <ContentTemplate> --%>
        <div>

            <%--OnSelectedIndexChanged="grdMutationFinal_SelectedIndexChanged"  DataKeyNames="mutationid"
                OnRowDataBound="grdMutationFinal_RowDataBound" OnRowDeleting="grdMutationFinal_RowDeleting" AutoGenerateDeleteButton="true"--%>

            <asp:GridView ID="grdDocument" runat="server" AllowPaging="false" Width="988px" DataKeyNames="villagecode,docno,documentcode,uploaddoccode" CssClass="table table-striped table-bordered table-condensed"
                AutoGenerateColumns="false" OnRowCommand="grdDocument_RowCommand" OnRowDataBound="grdDocument_RowDataBound" >
                <Columns>
                    <asp:BoundField DataField="actionpoints" HeaderText="Action Points" />
                    <asp:TemplateField HeaderText="Iteration 1">
                        <ItemTemplate>
                            <asp:LinkButton ID="linkDownload0" Enabled='<%# !string.IsNullOrEmpty(Eval("value").ToString()) ? true : false%>' CommandName="download" ToolTip='<%# Eval("check")%>' CommandArgument='<%# Eval("value")%>' Visible='<%# Eval("check").ToString() == "download" ? true : false %>' Text='<%# Eval("docname")%>' runat="server"></asp:LinkButton>
                            <asp:RadioButtonList ID="rblApproval0" RepeatDirection="Horizontal" Enabled='<%# Eval("iterationno").ToString() == "1" ? true : false %>' ToolTip='<%# Eval("check")%>' Visible='<%# Eval("check").ToString() == "approval" ? true : false %>' runat="server">
                                <asp:ListItem Text="Yes" Value="Yes"></asp:ListItem>
                                <asp:ListItem Text="No" Value="No"></asp:ListItem>
                            </asp:RadioButtonList>
                            <asp:FileUpload ID="fuQueryUpload0" Enabled='<%# Eval("iterationno").ToString() == "1" ? true : false %>' ToolTip='<%# Eval("check")%>' Visible='<%# Eval("check").ToString() == "query" ? true : false %>' runat="server" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Iteration 2">
                        <ItemTemplate>
                            <asp:LinkButton ID="linkDownload1" CommandName="download1" Enabled='<%# !string.IsNullOrEmpty(Eval("value").ToString()) ? true : false%>' ToolTip='<%# Eval("check")%>' CommandArgument='<%# Eval("value1")%>' Visible='<%# Eval("check").ToString() == "download" ? true : false %>' Text='<%# Eval("docname1")%>' runat="server"></asp:LinkButton>
                            <asp:RadioButtonList ID="rblApproval1" RepeatDirection="Horizontal" Enabled='<%# Eval("iterationno").ToString() == "2" ? true : false %>' ToolTip='<%# Eval("check")%>' Visible='<%# Eval("check").ToString() == "approval" ? true : false %>' runat="server">
                                <asp:ListItem Text="Yes" Value="Yes"></asp:ListItem>
                                <asp:ListItem Text="No" Value="No"></asp:ListItem>
                            </asp:RadioButtonList>
                            <asp:FileUpload ID="fuQueryUpload1" ToolTip='<%# Eval("check")%>' Enabled='<%# Eval("iterationno").ToString() == "2" ? true : false %>' Visible='<%# Eval("check").ToString() == "query" ? true : false %>' runat="server" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Iteration 3">
                        <ItemTemplate>
                            <asp:LinkButton ID="linkDownload2" CommandName="download2" Enabled='<%# !string.IsNullOrEmpty(Eval("value").ToString()) ? true : false%>' ToolTip='<%# Eval("check")%>' CommandArgument='<%# Eval("value2")%>' Visible='<%# Eval("check").ToString() == "download" ? true : false %>' Text='<%# Eval("docname2")%>' runat="server"></asp:LinkButton>
                            <asp:RadioButtonList ID="rblApproval2" RepeatDirection="Horizontal" Enabled='<%# Eval("iterationno").ToString() == "3" ? true : false %>' ToolTip='<%# Eval("check")%>' Visible='<%# Eval("check").ToString() == "approval" ? true : false %>' runat="server">
                                <asp:ListItem Text="Yes" Value="Yes"></asp:ListItem>
                                <asp:ListItem Text="No" Value="No"></asp:ListItem>
                            </asp:RadioButtonList>
                            <asp:FileUpload ID="fuQueryUpload2" ToolTip='<%# Eval("check")%>' Enabled='<%# Eval("iterationno").ToString() == "3" ? true : false %>' Visible='<%# Eval("check").ToString() == "query" ? true : false %>' runat="server" />
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
        <%--</contenttemplate>
              <Triggers> 
              <asp:PostBackTrigger controlid="Grid1"/> 
             </Triggers> 
        </asp:updatepanel>--%>
        <br />
        <div class="row">
            <div class="col-sm-2">
                <asp:Button ID="btnSave" runat="server" Text="Save" Visible="false" Height="30px" Width="75px" OnClick="btnSave_Click" />&nbsp;
                                <asp:Button ID="btnReset" runat="server" Visible="false" Text="Reset" Height="30px" Width="75px" OnClick="btnReset_Click" />
            </div>
            <div class="col-sm-3">
            </div>
            <div class="col-sm-2">
            </div>
            <div class="col-sm-2">
            </div>
        </div>
        <br />
        <br />
    </div>
</asp:Content>
